<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\AddNewFact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var bool                  $can_upload_media
 * @var Collection<int,Media> $individual_media
 * @var Individual            $record
 * @var Tree                  $tree
 */
?>

<?php if ($individual_media->isNotEmpty() || $tree->getPreference('USE_SILHOUETTE') === '1') : ?>
    <div class="col-sm-3 mn-indi-image-container">
        <?php if ($individual_media->isEmpty()) : ?>
            <div class="img-thumbnail mn-indi-silhouette">
                <i class="wt-individual-silhouette wt-individual-silhouette-<?= strtolower($record->sex()) ?> wt-icon-flip-rtl w-100"></i>
            </div>
        <?php elseif ($individual_media->count() === 1) : ?>
            <?= $individual_media->first()->displayImage(200, 260, 'crop', ['class' => 'img-thumbnail img-fluid w-100']) ?>
        <?php else : ?>
            <div id="individual-images" class="carousel slide" data-bs-interval="false">
                <div class="carousel-inner">
                    <?php foreach ($individual_media as $n => $media_file) : ?>
                        <div class="carousel-item <?= $n === 0 ? 'active' : '' ?>">
                            <?= $media_file->displayImage(200, 260, 'crop', ['class' => 'img-thumbnail img-fluid w-100']) ?>
                        </div>
                    <?php endforeach ?>
                </div>
                <button type="button" class="carousel-control-prev" data-bs-target="#individual-images" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden"><?= I18N::translate('previous') ?></span>
                </button>
                <button type="button" class="carousel-control-next" data-bs-target="#individual-images" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden"><?= I18N::translate('next') ?></span>
                </button>
            </div>
        <?php endif ?>

        <?php if ($can_upload_media) : ?>
            <div class="mn-add-media mt-2">
                <a href="<?= e(route(AddNewFact::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref(), 'fact' => 'OBJE'])) ?>">
                    <span class="d-flex align-items-center justify-content-center gap-2">
                        <span><?= view('icons/add') ?></span>
                        <span><?= I18N::translate('Add a media object') ?></span>
                    </span>
                </a>
            </div>
        <?php endif ?>
    </div>
<?php endif ?>
