<?php

use Fisharebest\Webtrees\Webtrees;

?>

<meta charset="UTF-8">
<meta name="csrf" content="<?= e(csrf_token()) ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="<?= e($meta_robots) ?>">
<meta name="generator" content="<?= e(Webtrees::NAME) ?> <?= e(Webtrees::VERSION) ?>">
<meta name="description" content="<?= e($meta_description) ?>">
<meta name="theme-color" content="#0b0e17">
