<?php

use Fisharebest\Webtrees\Module\ModuleGlobalInterface;
use Fisharebest\Webtrees\Module\ModuleThemeInterface;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\View;

?>

<script src="<?= e(asset('js/vendor.min.js')) ?>"></script>
<script src="<?= e(asset('js/webtrees.min.js')) ?>"></script>
<script src="<?= e(Registry::container()->get(ModuleThemeInterface::class)->assetUrl('js/noctis.js')) ?>"></script>

<?= View::stack('javascript') ?>

<?= Registry::container()->get(ModuleService::class)->findByInterface(ModuleGlobalInterface::class)->map(static function (ModuleGlobalInterface $module): string {
    return $module->bodyContent();
})->implode('') ?>
